### ISSUE TITLE
Exand & collapse chart of accounts

### ISSUE THREAD

**Issue by medhatelmasry** [medhatelmasry/GoodBooks#17]
When a top level account is clicked then the sub-accounts should expand like an accordion.

**Comment by medhatelmasry** [comment]
![image](https://github.com/medhatelmasry/GoodBooks/assets/1821250/4cb5e600-20ef-46ab-9797-2694b3d69e49)

**Comment by ydongchoi** [comment]
## Reference
https://www.ag-grid.com/angular-data-grid/grouping-opening-groups/
