### ISSUE TITLE
Bug when saving a customer on deployed application

### ISSUE THREAD

**Issue by ydongchoi** [medhatelmasry/GoodBooks#28]
HttpRequestException: Connection refused (localhost:8001)

![image](https://github.com/medhatelmasry/GoodBooks/assets/84194034/62727eee-48d2-4b98-992c-803aad0b5c0b)

**Comment by medhatelmasry** [comment]
Fixed. The URL for the API service was hard-coded. The code was changed so that it is read from the environment variable.
