### ISSUE TITLE
No proper highlighting when selecting a transaction

### ISSUE THREAD

**Issue by medhatelmasry** [medhatelmasry/GoodBooks#52]
Recreate issue:

Accounts Receivable >> Sales Receipts >> Click on an existing transaction

There is no background color scheme that indicates that the line item is selected.

**Comment by EbodShojaei** [comment]
Thanks, Medhat. I will fix this.

**Comment by EbodShojaei** [comment]
This has been resolved! Push will be made post-approval 🚀

- Light blue background on click
- Light grey background on hover (optional)

![image](https://github.com/user-attachments/assets/c4d50418-8984-46cc-ac5c-0db8fb1a0662)
