### ISSUE TITLE
General Ledger >> Accounts

### ISSUE THREAD

**Issue by medhatelmasry** [medhatelmasry/GoodBooks#7]
Display Parent >> Children relationship 

based on data found in the dbo.Account table in the database.

**Comment by medhatelmasry** [comment]
[chart-of-accounts.pdf](https://github.com/medhatelmasry/GoodBooks/files/14256094/chart-of-accounts.pdf)

This is what the chart of accounts look like in Quick Books.

**Comment by Rai-Sahil** [comment]
Chart of accounts tab is showing all the accounts even with parent child relation.
